DROP TABLE CONTACT IF EXISTS;
DROP TABLE STATUS IF EXISTS;
DROP TABLE COMPANY IF EXISTS;
CREATE TABLE STATUS (
  ID INTEGER PRIMARY KEY,
  VERSION INTEGER,
  NAME VARCHAR(50)
);
CREATE TABLE COMPANY (
  ID INTEGER PRIMARY KEY,
  VERSION INTEGER,
  NAME VARCHAR(50)
);
CREATE TABLE CONTACT (
  ID INTEGER PRIMARY KEY,
  VERSION INTEGER,
  EMAIL VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  COMPANY_ID INTEGER,
  STATUS_ID INTEGER,
  CONSTRAINT FK_CONTACT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID),
  CONSTRAINT FK_CONTACT_STATUS FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID)
);
